// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATZNAf6lIK4m7lTQczsE8nPqweYxM8v2g',
    appId: '1:548190410750:web:8e62a97adff6da2f13d2af',
    messagingSenderId: '548190410750',
    projectId: 'dsta4minions-176b0',
    authDomain: 'dsta4minions-176b0.firebaseapp.com',
    storageBucket: 'dsta4minions-176b0.firebasestorage.app',
    measurementId: 'G-V2W1QJX9LM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFOMjMCy0hZsufpKdkxFBIaaBHi4ElTwE',
    appId: '1:548190410750:android:6e20aa835a13d65513d2af',
    messagingSenderId: '548190410750',
    projectId: 'dsta4minions-176b0',
    storageBucket: 'dsta4minions-176b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCE9Wrk5B9W9Xc75nrJxuy3Ex6EoemkKI',
    appId: '1:548190410750:ios:23596ba5b1442b2213d2af',
    messagingSenderId: '548190410750',
    projectId: 'dsta4minions-176b0',
    storageBucket: 'dsta4minions-176b0.firebasestorage.app',
    iosBundleId: 'com.example.kakialert',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCE9Wrk5B9W9Xc75nrJxuy3Ex6EoemkKI',
    appId: '1:548190410750:ios:23596ba5b1442b2213d2af',
    messagingSenderId: '548190410750',
    projectId: 'dsta4minions-176b0',
    storageBucket: 'dsta4minions-176b0.firebasestorage.app',
    iosBundleId: 'com.example.kakialert',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATZNAf6lIK4m7lTQczsE8nPqweYxM8v2g',
    appId: '1:548190410750:web:4ae8fa29fcba81a013d2af',
    messagingSenderId: '548190410750',
    projectId: 'dsta4minions-176b0',
    authDomain: 'dsta4minions-176b0.firebaseapp.com',
    storageBucket: 'dsta4minions-176b0.firebasestorage.app',
    measurementId: 'G-G5W70DMSPF',
  );
}
